### ISSUE TITLE
Reorganize Project and Introduce SSE routes, settings page, and Rune set up.

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/dboard#17]
Wire up one widget within the new system structure.

## Tasks

- [ ] File Structure
- [ ] Server Data Fetching
- [ ] Server Data Processing
- [ ] Client State Management
- [ ] Create Issues for additional features:
  - [ ] Saving to Disk
  - [ ] Returning Custom Data Structures - based on configuration in settings.json/store
  - [ ] Using `sqlite` rather than a flat `.json` file — potentially allowing the use of `settings.json` for quickstart

### File Structure

```shell
- lib/stores
- routes/api
	- stream
		- [endpoint]
			- +server.ts
- routes/settings
	- streams
		- +page.ts
```

Create helper functions as needed.

### General Focus Areas

Concentrate on moving as much data fetching and processing to the server as possible. The client will update global state, when SSE returns events for its corresponding configuration.
